### ISSUE TITLE
Feature request: Require a certain threshold of stars before displaying "also forked to"

### ISSUE THREAD

**Issue by Ajedi32** [musically-ut/lovely-forks#11]
It would be nice if there was a configuration option you could set to require a minimum number of forks before the "also forked to" text is displayed. I don't really need to be notified that there's a fork with 1 or two stars of a popular repo that has 2k+ stars and a hundred or so forks - especially if the fork isn't more recently updated than the main repo.

**Comment by musically-ut** [comment]
I've been playing with the idea of adding an 'options' page myself. However, I couldn't settle on what *knobs* it should have. 

Now, with the update flame icon + usage of localStorage, the *knobs* can be decided with more clarity. I am thinking about having two **options**/*knobs*:

  - Minimum number of stars for a fork to be considered notable.
  - Whether to consider forks older than upstream notable or not. (a checkbox)

This will cover your use-case. Would you like to have more control over the options?

**Comment by Ajedi32** [comment]
Yes, assuming forks that aren't notable aren't shown, that would cover my use case.

**Comment by JaKXz** [comment]
+1 for this, I'd even say a minimum of 5 is a reasonable default.

**Comment by musically-ut** [comment]
@JaKXz @Ajedi32 I've recently released version `3.1.0` of the plugin on Chrome Webstore. I've submitted the new version to Firefox addons as well, but that process may take several days.

Whenever you get the update, could you verify that the preference is working as desired so that we may close this issue?

Thanks!

**Comment by Ajedi32** [comment]
Yep, works great!
