### ISSUE TITLE
Don't show for private repositories

### ISSUE THREAD

**Issue by JaKXz** [musically-ut/lovely-forks#12]
it would be great if the extension didn't make any calculations if the repo being looked at is private.

**Comment by musically-ut** [comment]
Interesting. I don't have a private repo handy to test this, but I will try to lay my hands on some. 

In the meanwhile, does this extension break the user experience on Github in someway on private repos by throwing errors or messing up the display?

**Comment by JaKXz** [comment]
@musically-ut it doesn't break anything, but it does just display "no information" string, which isn't really helpful.

**Comment by musically-ut** [comment]
Ah, the error message _actually_ is that Github didn't provide any information about the repo. I think I just should keep the place blank instead of showing `"no information"` there.
