### ISSUE TITLE
Create official seamonkey xpi.

### ISSUE THREAD

**Issue by onodera-punpun** [musically-ut/lovely-forks#18]
I've been using a converted version (using http://addonconverter.fotokraina.com/) of this addon for a while now and it works perfectly, the converter does the following:

```
    install.rdf	
        Added SeaMonkey to list of supported applications
        Changed extension name
    /META-INF	
        Removed META-INF folder to remove certificate check on installation
```

**Comment by musically-ut** [comment]
Thanks for testing it on Seamonkey. :)

Would it be possible for you to make a PR for this? Preferably, keeping the extra files in a separate folder and then copying them to the right place in the `Makefile` while building the `xpi`?

Otherwise, I'll eventually get around to it.

**Comment by onodera-punpun** [comment]
I just send a PR, I didn't test this myself since I don't have jpm, but I'm fairly sure it will work.

**Comment by musically-ut** [comment]
Oh. That seems simpler than I thought it would be (i.e. no `install.rdf`).

I'll test it on a local Linux machine and merge it in. Thanks!

**Comment by onodera-punpun** [comment]
Yeah I could not find install.rdf, so I think that file gets generated from the package.json file, since it's the only file where the browser and version get specified.

**Comment by musically-ut** [comment]
I'm afraid I am running into [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1149775) while testing it with SeaMonkey 2.39 on my Mac OSX. I think it would be best to wait before they release a new version I can verify that this works on before shipping it.

I'll keep this (and the PR #20) open till then.

**Comment by onodera-punpun** [comment]
SeaMonkey 2.40 has just been released last week, and it seems that it has been fixed in (according to the bug reports at least), I'll edit my PR accordingly.

**Comment by musically-ut** [comment]
@onodera-punpun I just got an e-mail confirming that the plugin in available on the [SeaMonkey addons store](https://addons.mozilla.org/en-US/seamonkey/addon/lovely-forks/?src=search). 

It would be great if you could review/rate it there. :)
