### ISSUE TITLE
Renamed forks

### ISSUE THREAD

**Issue by Mottie** [musically-ut/lovely-forks#19]
I noticed that when I load my tablesorter repo (https://github.com/Mottie/tablesorter), the most-popular fork (https://github.com/mikebryant/django-jquery-tablesorter) is no longer showing up because it is renamed... so the compare function isn't finding it:

> Failed to load resource: the server responded with a status of 404 (Not Found)
> https://api.github.com/repos/Mottie/tablesorter/compare/Mottie:django...mikebryant:django
> lovely-forks: Github API returned status: 404 contentscript.js:335

**Comment by musically-ut** [comment]
Thanks for the report!

#17 will fix it. I'll deploy it over the weekend, if not earlier.

**Comment by musically-ut** [comment]
Should be fixed. Can you please confirm and close?

Thanks!

**Comment by Mottie** [comment]
Yep, working great! Thanks again!
