### ISSUE TITLE
Firefox and Opera 

### ISSUE THREAD

**Issue by ShalokShalom** [musically-ut/lovely-forks#27]
There is support for Firefox and Opera, maybe mention this in the README?

https://addons.opera.com/de/extensions/details/download-chrome-extension-9/

https://addons.mozilla.org/de/firefox/addon/lovely-forks/

**Comment by musically-ut** [comment]
Hi @ShalokShalom,

The Firefox addon link is already present in the README. I'll add the link re: Opera shortly.

Thanks!

**Comment by ShalokShalom** [comment]
I mean as an icon, like with Chrome. I actually wasnt aware of a Firefox add on, since i trusted this one.

**Comment by musically-ut** [comment]
@ShalokShalom I see.

Do you think this README looks better: https://github.com/musically-ut/lovely-forks/tree/improve-readme

Any suggestions on how to improve the text/presentation?

**Comment by ShalokShalom** [comment]
Perfect, this looks super awesome to me. 

Can you think about a word (combination), which describes the essence of this tool?
If yes, i would replace *notable* with it.

**Comment by musically-ut** [comment]
Hmm, I'll have to think about it.

Do you have any suggestions there?

**Comment by ShalokShalom** [comment]
No, my english is to buggy. :)

**Comment by musically-ut** [comment]
I've updated the README but haven't yet come up with a better word than "notable" forks.
I'll keep this issue open until we find something better. :)

**Comment by ShalokShalom** [comment]
useful?

**Comment by musically-ut** [comment]
"useful" is not quite what describes the other fork the best.

Looking at the examples in the screenshots, the other forks can be compatibility fixes, can be ports to other platforms, or can be a feature branch which the original doesn't have.

The use-case I had in mind was that when the original repo has been abandoned, the fork becomes the next maintained thing, but the examples were far more versatile than merely that.

"useful" just doesn't get that meaning across, I think. "Noteworthy" seems to encompass those use-cases better.

**Comment by ShalokShalom** [comment]
"The use-case I had in mind was that when the original repo has been abandoned, the fork becomes the next maintained thing, but the examples were far more versatile than merely that."

Then mention this in the text as well?
