### ISSUE TITLE
[Appearance] Indent or background color for forks

### ISSUE THREAD

**Issue by yfdyh000** [musically-ut/lovely-forks#30]
In my opinion, the current appearance is not enough to express the hierarchical relationship of forks, it should be indented or a light color background / pattern to be clearer.

**Comment by musically-ut** [comment]
Thanks for the suggestion!

However, I am not able to fully visualize what the indentation/coloration will look like. Could you please add a small mock up (with screenshots?) to help me along?

Thanks!

**Comment by yfdyh000** [comment]
I'm not sure if I understand what you mean. `padding-left: 1em;` may be good.

**Comment by musically-ut** [comment]
So something like this:

**Before:**

![](http://i.imgur.com/3xzHYbE.png)

**After:**

![](http://i.imgur.com/ogiFt4j.png)

?

**Comment by yfdyh000** [comment]
Yes, I think it might be clearer.

**Comment by musically-ut** [comment]
I've added the style change.

I'll release it after bundling it with a couple of other fixes.

Thanks!
