### ISSUE TITLE
Firefox addon: Migrate to WebExtensions

### ISSUE THREAD

**Issue by ohmyarch** [musically-ut/lovely-forks#31]
![](https://ptpb.pw/0qKP.png)

https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

**Comment by musically-ut** [comment]
Thanks for creating an issue. I plan to do it later this month.

**Comment by yfdyh000** [comment]
Any news?

In addition, maybe it can be made to an userscript for more users?

**Comment by musically-ut** [comment]
Converting fully to WebExtensions is on my TODO list. That would also help in resolving #11 as well.

However, unfortunately, converting it to a user-script is not; I don't use user-scripts myself. Hence, any contribution in that direction would be much appreciated! :)
