### ISSUE TITLE
Impossible to add the Chrome extension.

### ISSUE THREAD

**Issue by Alexandre-Nourissier** [musically-ut/lovely-forks#34]
The package is marked as invalid. 

Experienced with Chrome |  Version 59.0.3071.115 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/10888984/28499264-108b5c16-6fb2-11e7-846e-892109674297.png)

**Comment by musically-ut** [comment]
Ouch. Thanks for the report!
I'm updating the extension now.

**Comment by musically-ut** [comment]
I've verified that I'm able to install the extension from the Chrome store now.
I hope it works for everyone. (* fingers crossed *)

Thanks again for the report!

**Comment by Alexandre-Nourissier** [comment]
Good Job ! Thanks for your fast reaction.
