### ISSUE TITLE
Text is no longer aligned

### ISSUE THREAD

**Issue by bfred-it** [musically-ut/lovely-forks#35]
Native:

<img width="275" alt="" src="https://user-images.githubusercontent.com/1402241/28511955-422b1f9c-7082-11e7-8e17-480ca8049de4.png">

lovely forks:

<img width="267" alt="" src="https://user-images.githubusercontent.com/1402241/28511967-4c091a00-7082-11e7-8045-4ca09f77df56.png">

**Comment by musically-ut** [comment]
This was an explicit change requested in #30. Personally, both styles look okay to me.

Maybe @yfdyh000 will have some opinions about this?

**Comment by bfred-it** [comment]
It just looks misaligned to me. GitHub's own style on repos (which I matched years ago here) doesn't show any particular hierarchy either.

If anything, the base repo's larger style already **does** appear as hierarchically higher.

**Comment by yfdyh000** [comment]
I forgot the "Native" style from GitHub, but it is confusing for me, that like an original message from the repo / page, not extra info from the extension.

An user-option may to ease this issue, but I don't know what the default value should be.

**Comment by bfred-it** [comment]
But you know it's from the extension because you installed it. The point is that it should blend in with the hosting site, not be visibly off-place. This brings it to GitHub's default position. 

Most of the time the fork isn't even useful unless it's more recent, and at that point it will have a nice red flame to bring it to your attention.

**Comment by yfdyh000** [comment]
Uniform style is justified, although I prefer to have an indentation to indicate its hierarchy.

Another reason, the "Native" is child to parent, the extension is reversed, so I prefers it to shows this is a different tree structure.

**Comment by marsjaninzmarsa** [comment]
I like #30. If you find cleaner way, ok, but indentation was definitely positive change.

**Comment by musically-ut** [comment]
Thank you for your inputs!

Alright, I've decided to make it a preference on the plugin. I have that implemented on the `master` branch and I've chosen to stick to the default of not-indenting (after a discussion with @wereHamster offline).

I'll test out the plugin a bit more on a separate computer and then upload the new version to Chrome WebStore and Firefox Addons. In the meanwhile, you can check out the `master` branch and test-ride the implementation. Feedback, of course, is very welcome.  :)

Thanks again!

**Comment by musically-ut** [comment]
The extension is live on Firefox Addons and on the WebStore now.
