### ISSUE TITLE
jQuery missing from build 3.1.2 on Firefox

### ISSUE THREAD

**Issue by Jackymancs4** [musically-ut/lovely-forks#40]
Hello,
I'm actually not sure about the reasons behind https://github.com/musically-ut/lovely-forks/commit/ca02795b01857263dd53a8583c4ce6dfe948cd15, but jQuery is still a semantic-ui dependency.
This breaks the option page on firefox.
<img width="1003" alt="schermata 2018-02-07 alle 17 50 33" src="https://user-images.githubusercontent.com/6209647/35929370-a140d0f0-0c2f-11e8-98d6-3e232b028538.png">

Also I noticed that that build 3.1.2 was not available on the Chrome Store.

**Comment by Jackymancs4** [comment]
Fixed with #41 merge.

**Comment by musically-ut** [comment]
Build 3.1.2 was not available on Chrome because all it did was to un-obfuscate the code, without adding any features (to make Mozilla reviewers happy).

And, again, thanks for the fix!
