### ISSUE TITLE
I guess plugin stopped working at least in chrome

### ISSUE THREAD

**Issue by kortov** [musically-ut/lovely-forks#48]
Chrome 79.0.3945.117 (latest) 64bit, for example on https://github.com/tpope/vim-fugitive page got errors in the console 

``` 
chrome-extension://ialbpcipalajnakfondkflpkagbkdoib/webext/data/contentscript.js:106 lovely-forks: Looks like the layout of the GitHub page has changed.
getForksElement @ chrome-extension://ialbpcipalajnakfondkflpkagbkdoib/webext/data/contentscript.js:106
chrome-extension://ialbpcipalajnakfondkflpkagbkdoib/webext/data/contentscript.js:163 lovely-forks: Unable to find the lovely-forks loading indicator during action showing details
safeUpdateDOM @ chrome-extension://ialbpcipalajnakfondkflpkagbkdoib/webext/data/contentscript.js:163

```

![image](https://user-images.githubusercontent.com/6348215/72323462-3e008c00-36c2-11ea-89a8-4005b2a2ee8d.png)

**Comment by musically-ut** [comment]
Eek!

Thanks for reporting this, I will dig into it.

**Comment by musically-ut** [comment]
I've figured out the change here: https://github.com/musically-ut/lovely-forks/commit/f3ba9e356523b9bb8dcf345a65c06c4e126fb22b, but am not fully satisfied with the solution. If nothing better comes up, I'll publish the plugin with this fix later today.

Thanks for noticing this!

**Comment by kortov** [comment]
thank you anyway :) I saw too that github changed CSS class naming

**Comment by musically-ut** [comment]
I'm seeing the same sort of scrambled class names at on other React with CSS-in-JS kind websites. Hence, I don't think that there will be a better way to get to the elements and this fix will be the fix.

**Comment by musically-ut** [comment]
I've published version `3.4.0` to Chrome Webstore with this fixed. The Firefox release will take a bit more time as I test it and then push it through the verification pipeline (I might as well implement some other fixes while I am at it).

If you use it on Chrome, could you please close the issue after verifying that it works for you?

Thanks!

**Comment by kortov** [comment]
It's alive! :D 
![image](https://user-images.githubusercontent.com/6348215/72518775-71cce480-386f-11ea-905d-6accc05c0e4d.png)

**Comment by kortov** [comment]
Thank you for a promt fix and for the plugin
