### ISSUE TITLE
Doesn't work with new Github layout

### ISSUE THREAD

**Issue by MinusKube** [musically-ut/lovely-forks#53]
This extension doesn't seem to work anymore due to the new Github layout.

Nothing appears on the page, and two warnings are logged into the console:
![image](https://user-images.githubusercontent.com/13206601/88982501-bd555600-d2c8-11ea-9aec-4d98d61dd201.png)

**Comment by musically-ut** [comment]
🤦 

I'll get right on it over the weekend. Thanks for the report!

**Comment by kirsan31** [comment]
Yea just have installed chrome extension and it's not working :(

**Comment by musically-ut** [comment]
I spent sometime on it yesteday, but the fix is a bit non trivial; the class names have changed such that I will have to write a more intricate query. I'll finish it up today and post an update.

**Comment by musically-ut** [comment]
Will be making a release on Chrome WebStore and Firefox shortly. That should fix this issue. However, the selector I use is now un-comfortably fragile, so please be on the watch-out for regression!

Thanks!
