### ISSUE TITLE
Suggestions: make the text grayed out until mouseover + have smaller text size

### ISSUE THREAD

**Issue by darkred** [musically-ut/lovely-forks#60]
First, thank you for this very useful extension!

---

I'd like to make two suggestions about the text:
- to be initially grayed out (less opacity), and only make it normal on mouseover, and
- to have smaller size *(the same text size as in `forked from` - see the first screenshot in the end)*.

The `also forked to` text, not being grayed out, becomes distractive compared to the repo name, even though it's additional info: 
the most notable fork is surely very useful info, but less important that the original repo that the current one was forked from.

&nbsp;

Here is a screenshot comparison:

`forked from` (default by GitHub in forks)
![2020-11-23_222306](https://user-images.githubusercontent.com/723651/100011681-bfdd3d80-2dda-11eb-8839-6c256413310b.jpg)

`also forked to` (this extension)
![2020-11-23_222341](https://user-images.githubusercontent.com/723651/100011686-c23f9780-2dda-11eb-8926-7978da693ec4.jpg)

**Comment by musically-ut** [comment]
Indeed, you are right that the CSS formatting of this extension has drifted slightly since the new GitHub rebranding. 

I'll fix it this coming weekend. 

Thanks!

**Comment by darkred** [comment]
Thank you for the quick response.

How do you find my suggestion to make the text grayed out until mouseover ?

**Comment by musically-ut** [comment]
I would prefer to stick to GitHub's own styling as much as possible. 

I can see the argument that it is not as important as the repo-name itself, but find the argument from consistency marginally more compelling. 🙃

**Comment by darkred** [comment]
Offering it as an option, disabled by default?

**Comment by musically-ut** [comment]
I've changed the styling of the text to match the `forked from` in the extension. However, I haven't implemented the greying out partly because it is more work, and partly because we may need to change the grey based on light/dark mode. I don't want to throw in more GitHub layout-dependent features into the extension quite yet. :)
