### ISSUE TITLE
Blank panel bug in navbar

### ISSUE THREAD

**Issue by Christopher-Hayes** [musically-ut/lovely-forks#62]
Hello, there's this blank panel that shows in the navbar, below the notification bell.

In dark mode:
![image](https://user-images.githubusercontent.com/6013871/102137329-abfc8880-3e28-11eb-8f94-2fdadcdaa7f4.png)
In light mode:
![image](https://user-images.githubusercontent.com/6013871/102137364-b7e84a80-3e28-11eb-82c0-4981f82278b3.png)

CSS:
element classes: `.d-none.d-lg-block.mt-6.mr-3.Popover.top-0.right-0.box-shadow-medium.col-3`
![image](https://user-images.githubusercontent.com/6013871/102143256-b1aa9c00-3e31-11eb-9a3d-27b08d24514d.png)

![image](https://user-images.githubusercontent.com/6013871/102137490-e9611600-3e28-11eb-99ac-18739abc8c61.png)

Disabling/enabling the add-on shows that the styling below is being added to this element.
![image](https://user-images.githubusercontent.com/6013871/102143013-4bbe1480-3e31-11eb-8302-8b2f59f4235f.png)

Disabling the styling above removes the display bug:
![image](https://user-images.githubusercontent.com/6013871/102143137-80ca6700-3e31-11eb-82a4-a698b85f2027.png)

This is the code in question: https://github.com/musically-ut/lovely-forks/blob/6e9f0ee932505dfc2ffa3b9c25557889b253bf96/webext/data/style.css#L1:L4

Seems like this is a regression resulting from this bugfix: https://github.com/musically-ut/lovely-forks/issues/53

**Comment by musically-ut** [comment]
Wow. Thanks for the detailed analysis!

Indeed, that PR for the new GitHub layout seems to be the culprit here. However, I do not see it myself on my browser. Which browser are you using and are you using the extension or the user-script?

I'll investigate and try to replicate it myself and will ask you more questions.

**Comment by Christopher-Hayes** [comment]
I'm seeing it on Firefox 84 and Chrome 85, both using the browser addon/extension. Both extensions are running v3.5.0. An important detail I forgot to mention is I only see this when I open the page of a repo and I have the "Code" tab selected.

**Comment by musically-ut** [comment]
Excellent; I can now reproduce it. Thanks!
