### ISSUE TITLE
Too many lovely forkers with the same username and stars

### ISSUE THREAD

**Issue by zplusfour** [musically-ut/lovely-forks#64]
So I went to [microsoft/vscode](https://github.com/microsoft/vscode), and look at this:

![image](https://user-images.githubusercontent.com/73612690/106251937-4f113200-621e-11eb-973c-7b28b4eaf711.png)

This is probably a bug, please fix it, thanks!!

**Comment by musically-ut** [comment]
!

I don't see it on my browser :(

<img width="380" src="https://user-images.githubusercontent.com/502876/106265584-8cc68880-6227-11eb-82da-63905d7582ec.png" />

Can you tell me:

 1. which browser
 2. which OS
 3. which extension version 

you are using?

Thanks for the report!

**Comment by zplusfour** [comment]
sure

1. Chrome
2. Windows
3. 3.6.0

**Comment by musically-ut** [comment]
Do you happen to have any ad-blockers or some such running on the page as well?

The code has a hard check to make sure that it adds only one or zero elements. This can happen only if something is scrubbing the classnames the extension is adding to the tags.

Also, does this happen directly on page load or after navigating to other tabs (Issues/Pull Requests, etc.)?
Do you happen to have the console output when this happens too?

The bug has puzzled me.

**Comment by zplusfour** [comment]
Oh, I went to vscode again and I don't see it now :)

**Comment by zplusfour** [comment]
1. no I don't have any ad blocker, and github has no ads
2. um I went to microsoft to see their projects, I saw vscode and I clicked on it, that's it
3. I am sorry :(

**Comment by musically-ut** [comment]
Classic Heisenbug! :D 

I'll close this issue for now; let's pick it up again if it happens again. :)

Thanks for reporting it; I hope you report when it happens again; it may be a race condition somewhere in the code.

**Comment by zplusfour** [comment]
:D

yeah probably

**Comment by zplusfour** [comment]
oh no here we go again

![image](https://user-images.githubusercontent.com/73612690/106757283-d3a5eb00-6638-11eb-854c-ff1fcb5a2cc1.png)

**Comment by zplusfour** [comment]
Im verry sorry

**Comment by musically-ut** [comment]
:D 

No need to be sorry; now I just have to figure out how this is possible. I stay on GitHub all the time; I'll keep an eye out for this myself.

How frequently does it seem to happen?

**Comment by zplusfour** [comment]
Ok, good
Wait I have an idea
I am a JavaScript/TypeScript expert, I'll fork it and try to fix this, and if I fixed it, I'll make a pr

**Comment by musically-ut** [comment]
That would be awesome!

**Comment by zplusfour** [comment]
yeah!

**Comment by hauk92** [comment]
You can reproduce this by going to an issue page and then returning to the previous page.
For example go to https://github.com/microsoft/vscode/issues and wait for lovely forks to load, then go back to the issues page by clicking your "back" button in the browser - now two forks of the same name and author are shown. You can repeat this by going forward and back again and another fork will appear.

**Comment by musically-ut** [comment]
Aah, the key step was to hit the `back` button instead of just swapping between `Issues` and `Code` tabs.

Now that I can reproduce it, I can work on it. :)

Thanks @hauk92 !

**Comment by musically-ut** [comment]
Thanks to @Jorgen1040, this should be fixed in version 3.6.1 of the extension. I've uploaded it both to Firefox and Chrome, coming to a webstore near you soon!
