### ISSUE TITLE
Notify when the fork is more recently updated than the original repo

### ISSUE THREAD

**Issue by harrymvr** [musically-ut/lovely-forks#9]
I have found myself clicking on the *notable* fork, only to check if it has been updated more recently than the original repository. That would hint, especially for old repos, that maybe the project is now being actively developed by a different person.

 It would be nice if there would be an icon notifying such an occasion. My suggestion goes for the [octicon-flame](https://octicons.github.com/icon/flame/) in orange (#d26911).

Also, thanks for the really nice tool :+1:

**Comment by musically-ut** [comment]
Thanks for the idea and the feedback >_<

Having an extra indicator of recency sounds like a good idea.

However, the comparison of the last update times is going to cost one more API call (to determine when the current repo was last updated). I can gather that data from the DOM, but that is too fragile for my comfort.

The correct way (TM) to do it, I think, is to use the `localStorage` and cache the responses from the various Github API calls. These data can be expired in ~ 15 minutes (probably longer) as the state of the repository nor the forks is unlikely to change by much during this time.

I'll investigate this approach locally before I commit to fixing this issue.

Thanks again!

**Comment by musically-ut** [comment]
I have released a new version and the extension should update in a couple of hours. I'd love to hear your feedback on it. :)
